server:
  port: 2504
  servlet:
    context-path: /justAchieveVirtualAssistant

api:
  calorieninja:
    url: https://api.calorieninjas.com/v1/
    key: ePG30Bb+I8ZV7ofgX3IuVQ==AzS73ZdQAPXxKonk

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/justAchieveVirtualAssistant
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.poczta.onet.pl
    port: 587
    username: justachievevirtualassistant@onet.pl
    password: ENC(081tlkbH0WW76zNZl+uSuM9nTIrJmQCtpj5zHnHsSHD0QG1m+xWiHQ==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: secretkey

